#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Update ulimits
$basedir/ulimits/init

# Install node 
sudo su - root -c "$basedir/backend/node/init"

# Install vim
sudo su - root -c "$basedir/vim/init"

# Install nginx
sudo su - root -c "$basedir/backend/nginx/init"

# Install java
sudo su - root -c "$basedir/backend/java/init"

# Install py27
sudo su - root -c "$basedir/backend/python27/init"
