#!/bin/bash

# install nodejs 6, reference https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
sudo su - root -c "apt-get install curl"
sudo su - root -c "curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -"
sudo su - root -c "apt-get install -y nodejs"
sudo su - root -c "apt-get install -y nodejs-legacy"

# install build tools
sudo su - root -c "apt-get install -y build-essential"

# install less 
sudo su - root -c "npm install -g less"
