#!/bin/bash

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash

# Reference https://nodejs.org/en/download/package-manager/#nvm.
# Use `nvm` commands, e.g. `nvm install 9` or `nvm uninstall 9` for management.
