#!/bin/bash

wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash

# Reference https://nodejs.org/en/download/package-manager/#nvm.
# Use `nvm` commands, e.g. `npm install 8` or `npm uninstall 8` for management.
