#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "apt-get -y install nginx"
sudo su - root -c "cat $basedir/nginx_template.conf > /etc/nginx/nginx.conf"
sudo su - root -c "service nginx restart"

