#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "apt-get -y install vim"

# install pathogen 
mkdir -p ~/.vim/autoload ~/.vim/bundle 
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# initialize vimrc globally
sudo su - root -c "cat $basedir/vimrc_template > /etc/vim/vimrc"
