#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "apt-get -y install vim"
$basedir/install_jshint_plugin

sudo su - root -c "cat $basedir/vimrc_template > /etc/vim/vimrc"
