#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# sudo su - root -c "$basedir/../backend/node/init"

sudo su - root -c "npm install -g jshint"

mkdir -p ~/.vim/bundle/jshint/plugin
curl -LSso ~/.vim/bundle/jshint/plugin/jshint.vim https://raw.githubusercontent.com/walm/jshint.vim/master/plugin/jshint.vim
