#!/bin/bash

# install npm
sudo su - root -c "apt-get -y install npm"

# upgrade npm 
sudo su - root -c "curl -L https://npmjs.org/install.sh | sh"

# install less via npm
sudo su - root -c "npm install -g less"
