#!/bin/bash

# Note that Ubuntu has its own `pg_wrapper` binaries for PostgreSQL client commands, reference http://manpages.ubuntu.com/manpages/precise/man1/pg_wrapper.1.html

if [ $# -ne 2 ]; then 
	echo "Usage: $0 <postgres version> <cluster name>"
	exit 1
fi

version=$1
cluster=$2

sudo su - root -c "pg_ctlcluster $version $cluster stop"
