#!/bin/bash

if [ $# -ne 1 ]; then 
	echo "Usage: $0 <dbname>"
	exit 1
fi

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

dbname=$1

sudo su - postgres -c "createdb $dbname -E unicode -T template0"

schema='public'
# grant proper privileges of tables in database.schema, e.g. test.public to users 'cu' and 'rep'
$basedir/grant_read_write $dbname $schema cu
$basedir/grant_read_only $dbname $schema rep
