#!/bin/bash

if [ $# -ne 3 ]; then 
	echo "Usage: $0 <dbname> <schema> <psql user>"
	exit 1
fi

dbname=$1
schema=$2
user=$3

sudo su - postgres -c "psql -d $dbname -c \"GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA $schema TO $user;\""
