#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

postgres_version='9.5'

sudo su - root -c "apt-get install -y pgpool2"

sudo su - root -c "chmod -R u+s /etc/pgpool2"
sudo su - root -c "chmod -R g+s /etc/pgpool2"

sudo su - root -c "cat $basedir/pgpool_master_slave_template.conf > /etc/pgpool2/pgpool.conf"
sudo su - root -c "cat $basedir/pgpool_hba_template.conf > /etc/pgpool2/pool_hba.conf"

$basedir/pgpool_stop
$basedir/pgpool_start
