#!/bin/bash

# Note that Ubuntu has its own `pg_wrapper` binaries for PostgreSQL client commands, reference http://manpages.ubuntu.com/manpages/precise/man1/pg_wrapper.1.html

version=9.5

sudo su - root -c "pg_ctlcluster -m fast $version main stop"
