#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "apt-get install -y pgpool2"

sudo su - root -c "chmod -R u+s /etc/pgpool2"
sudo su - root -c "chmod -R g+s /etc/pgpool2"

sudo su - root -c "cat $basedir/pgpool2_ctrl_replication_template.conf > /etc/pgpool2/pgpool.conf"
sudo su - root -c "cat $basedir/pool_hba_template.conf > /etc/pgpool2/pool_hba.conf"

$basedir/start_pgpool2_ctrl
