#!/bin/bash

sudo su - root -c "apt-get remove erlang"
sudo su - root -c "apt-get purge erlang"
sudo su - root -c "apt-get autoremove"
sudo su - root -c "wget https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_19.0-1~ubuntu~trusty_amd64.deb"
sudo su - root -c "dpkg -i esl-erlang_19.0-1~ubuntu~trusty_amd64.deb"
sudo su - root -c "apt-get -f install"
sudo su - root -c "rm esl-erlang_19.0-1~ubuntu~trusty_amd64.deb"
