#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

sudo su - root -c "apt-get -y install curl"
sudo su - root -c "apt-get -y install autotools-dev"
sudo su - root -c "apt-get -y install autoconf"
sudo su - root -c "apt-get -y install libncurses-dev"
sudo su - root -c "apt-get -y install libxml2 libxml2-dev"
sudo su - root -c "apt-get -y install libxslt1.1"
sudo su - root -c "apt-get -y install libssl-dev"

version=19.1
sudo su - root -c "curl -o $basedir/otp_src_$version.tar.gz http://erlang.org/download/otp_src_$version.tar.gz";
sudo su - root -c "tar -zxf $basedir/otp_src_$version.tar.gz -C $basedir"

sudo su - root -c "cd $basedir/otp_src_$version; export ERL_TOP=$basedir/otp_src_$version; ./configure; export LANG=C; make; make install;"

sudo su - root -c "rm -rf $basedir/otp_src_$version.tar.gz; rm -rf $basedir/otp_src_$version"

# To uninstall, remove the binaries and libraries in /usr/local/bin, and /usr/local/lib/erlang. Reference https://github.com/erlang/otp/blob/maint/HOWTO/INSTALL.md#configuring.

# If documentation is installed, one should also check /usr/local/etc/man.d, /usr/local/etc/rc.d and /usr/local/share/doc/erlang.
: <<'END'
sudo su - root -c "rm -rf /usr/local/bin/ct_run"
sudo su - root -c "rm -rf /usr/local/bin/dialyzer"
sudo su - root -c "rm -rf /usr/local/bin/epmd"
sudo su - root -c "rm -rf /usr/local/bin/erl"
sudo su - root -c "rm -rf /usr/local/bin/erlc"
sudo su - root -c "rm -rf /usr/local/bin/escript"
sudo su - root -c "rm -rf /usr/local/bin/run_erl"
sudo su - root -c "rm -rf /usr/local/bin/to_erl"
sudo su - root -c "rm -rf /usr/local/bin/typer"

sudo su - root -c "rm -rf /usr/local/lib/erlang"
END
