#!/bin/sh
sudo su - root -c "apt-get install python-software-properties"
sudo su - root -c "add-apt-repository ppa:ondrej/php"
sudo su - root -c "apt-get update"

toPurgeVer=5
toPurge="php$toPurgeVer libapache2-mod-php$toPurgeVer php$toPurgeVer php$toPurgeVer-cli php$toPurgeVer-common php$toPurgeVer-curl php$toPurgeVer-gd php$toPurgeVer-imap php$toPurgeVer-intl php$toPurgeVer-json php$toPurgeVer-mcrypt php$toPurgeVer-mysql php$toPurgeVer-pspell php$toPurgeVer-readline php$toPurgeVer-sqlite php$toPurgeVer-opcache php$toPurgeVer-zip"

sudo su - root -c "apt-get -y purge $toPurge"

ver=7.0

sudo su - root -c "apt-get install php$ver"

# Install MySQL binding.
sudo su - root -c "apt-get install php$ver-mysql"

# Install ZIP extension. 
sudo su - root -c "apt-get install php$ver-zip"

# Install fpm.
sudo su - root -c "apt-get install php$ver-fpm"
