#!/bin/bash

if [ $# -ne 3 ]; then 
  echo "Usage: $0 <dbname> <mysql user> <IP or FQDN>"
  exit 1
fi

dbname=$1
user=$2
addr=$3

cmd="GRANT ALL PRIVILEGES ON "
cmd+=$dbname
cmd+=".* TO '"
cmd+=$user
cmd+="'@'"
cmd+=$addr
cmd+="';"
mysql -v -uroot -e "$cmd"
