#!/bin/bash

if [ $# -ne 4 ]; then 
  echo "Usage: $0 <dbname> <mysql user> <IP or FQDN> <password>"
  exit 1
fi

dbname=$1
user=$2
addr=$3
password=$4

cmd="GRANT ALL PRIVILEGES ON "
cmd+=$dbname
cmd+=".* TO '"
cmd+=$user
cmd+="'@'"
cmd+=$addr
cmd+="' IDENTIFIED BY '"
cmd+=$password
cmd+="';" 
mysql -v -uroot -e "$cmd"
