#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
ppaVer=0.8.7-1
cd $basedir && wget https://repo.mysql.com/mysql-apt-config_$ppaVer_all.deb
sudo dpkg -i $basedir/mysql-apt-config_$ppaVer_all.deb

sudo su - root -c "apt-get update"
sudo su - root -c "apt-get -y install mysql-server"

echo "\nRemoving password for MySQL user \"root@localhost\", please enter your old password for it.\n"
mysql -uroot -p -e "SET PASSWORD FOR root@localhost=PASSWORD('');"

# Reference https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html. 
sudo su - root -c "mysqld --initialize --user=mysql --datadir=/var/lib/mysql"
sudo su - root -c "cat $basedir/mysqld_template.conf > /etc/my.cnf"

sudo su - root -c "$basedir/start"

# wait for mysqld starting up
sudo su - root -c "sleep 5"

# remote access is disabled by default
mysql -uroot -e "CREATE USER 'cu'@'localhost'"
mysql -uroot -e "CREATE USER 'rep'@'localhost'"

dbname='test'
mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $dbname"

sudo su - root -c "$basedir/grant_read_write $dbname cu localhost"
sudo su - root -c "$basedir/grant_read_only $dbname rep localhost"
