#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$basedir/uninstall

ppaVer=0.8.7-1
debFilename=mysql-apt-config_"$ppaVer"_all.deb
debURI=https://repo.mysql.com/$debFilename
cd $basedir && wget $debURI
sudo dpkg -i $basedir/$debFilename

sudo su - root -c "apt-get update"
sudo su - root -c "apt-get -y install mysql-server"

printf "\nRemoving password for MySQL user \"root@localhost\", please enter your old password for it.\n"
mysql -uroot -p -e "SET PASSWORD FOR root@localhost=PASSWORD('');"

sudo su - $mysqlOsUser -c "mysql_upgrade"

# Reference https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html. 
mysqlOsUser=mysql
mysqlOsGroup=mysql

logFilepath="/var/log/mysqld.log"
sudo su - root -c "touch $logFilepath"
sudo su - root -c "chown -R $mysqlOsUser:$mysqlOsGroup $logFilepath"
sudo su - root -c "chmod -R 774 $logFilepath"

# wait for mysqld starting up
sudo su - root -c "sleep 5"

# remote access is disabled by default
mysql -uroot -e "CREATE USER 'cu'@'localhost'"
mysql -uroot -e "CREATE USER 'rep'@'localhost'"

dbname='test'
mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $dbname"

sudo su - root -c "$basedir/grant_read_write $dbname cu localhost"
sudo su - root -c "$basedir/grant_read_only $dbname rep localhost"
