#!/bin/bash
cmdSudo=
basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$basedir/uninstall

# Reference https://dev.mysql.com/downloads/repo/apt/.
ppaVer=0.8.10-1
debFilename=mysql-apt-config_"$ppaVer"_all.deb
debURI=https://repo.mysql.com/$debFilename
cd $basedir && wget $debURI
$cmdSudo dpkg -i $basedir/$debFilename

$cmdSudo su - root -c "apt-get update"
$cmdSudo su - root -c "apt-get -y --force-yes install mysql-server"

# Reference https://dev.mysql.com/doc/refman/5.7/en/data-directory-initialization-mysqld.html. 
mysqlOsUser=mysql
mysqlOsGroup=mysql

logFilepath="/var/log/mysqld.log"
$cmdSudo su - root -c "touch $logFilepath"
$cmdSudo su - root -c "chown -R $mysqlOsUser:$mysqlOsGroup $logFilepath"
$cmdSudo su - root -c "chmod -R 774 $logFilepath"

$cmdSudo su - root -c "$basedir/stop"
$cmdSudo su - root -c "$basedir/start"

# wait for mysqld starting up
$cmdSudo su - root -c "sleep 5"

printf "\nRemoving password for MySQL user \"root@localhost\", please enter your old password for it.\n"
mysql -uroot -p -e "SET PASSWORD FOR root@localhost=PASSWORD('');"

$cmdSudo su - $mysqlOsUser -c "mysql_upgrade"

# wait for mysqld starting up
$cmdSudo su - root -c "sleep 5"

# remote access is disabled by default
mysql -uroot -e "CREATE USER 'cu'@'localhost'"
mysql -uroot -e "CREATE USER 'rep'@'localhost'"

dbname='test'
mysql -uroot -e "CREATE DATABASE IF NOT EXISTS $dbname"

sudo su - root -c "$basedir/grant_read_write $dbname cu localhost"
sudo su - root -c "$basedir/grant_read_only $dbname rep localhost"
