#!/bin/bash

if [ $# -ne 1 ]; then 
  echo "Usage: $0 <version, e.g. \"1.9\", \"1.10\">"
  exit 1
fi

version=$1
GO_BIN_PATH="/usr/lib/go-$version/bin"

# Check against padded $PATH.
if [[ ":$PATH:" != *":${GO_BIN_PATH}:"* ]]; then
  NEW_PATH="${GO_BIN_PATH}:${PATH}"
  echo "New value for \$PATH is now $NEW_PATH."
  export PATH=$NEW_PATH
else
  echo "No need to update \$PATH."
fi
